name: Build
on:
  # run it on push to the default repository branch
  push:
    branches: [master]
  # run it during pull request
  pull_request:

env:
    SHELLSPEC_VERSION: 0.28.1

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.25.0
          trivy -v

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "entrypoint.sh"
          severity: "error"

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s ${{ env.SHELLSPEC_VERSION }} --yes

      - name: Run shellspec
        run: shellspec
