name: Build
on:
  # run it on push to the default repository branch
  push:
    branches: [master]
  # run it during pull request
  pull_request:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "entrypoint.sh"
          severity: "error"

      - name: check spell
        uses: codespell-project/actions-codespell@master
        with:
          skip: ''

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
