name: Build
on:
  # run it on push to the default repository branch
  push:
    branches: [master]
  # run it during pull request
  pull_request:

env:
    SHELLSPEC_VERSION: 0.28.1

jobs:
  build:
    name: Build image
    runs-on: ubuntu-20.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "entrypoint.sh"
          severity: "error"

      - name: check spell
        uses: codespell-project/actions-codespell@master
        with:
          skip: ''

      - name: Install shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s ${{ env.SHELLSPEC_VERSION }} --yes

      - name: Run shellspec
        run: make docker-test
